apiVersion: apps/v1
kind: Deployment
metadata:
  name: vRisingServerDeployment
spec:
  selector:
    matchLabels:
      app: vRisingServer
  template:
    metadata:
      labels:
        app: vRisingServer
    spec:
      volumes:
        - name: persistendata
          persistentVolumeClaim:
            claimName: vrisingpersistendata
        - name: serverdata
          persistentVolumeClaim:
            claimName: vrisingserverdata
      containers:
      - name: vrisingservercontainer
        image: example.com/path/to/image:tag
        volumeMounts:
          - name: persistentData
            mountPath: /home/steam/vrising/persistentdata
          - name: serverData
            mountPath: /home/steam/vrising/server
        envFrom:
          - configMapRef:
              name: vrisingcm
          - secretRef:
              name: vrisingsecret
        resources:
          limits:
            memory: "8Gi"
            cpu: "4"
        livenessProbe:
          exec:
            command:
              - /bin/bash
              - -c
              - /home/steam/files/scripts/healthcheck.sh
          initialDelaySeconds: 360
          periodSeconds: 20
        ports:
        - protocol: UDP
          containerPort: 9876
        - protocol: TCP
          containerPort: 9876
        - protocol: UDP
          containerPort: 9877
