--- 
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vrising
commonLabels:
  app: vRisingServer
resources:
  - configMap.yaml
  - deployment.yaml
  - secret.yaml
  - nodePort.yaml
  - networkPolicy.yaml
  - pvc.yaml