apiVersion: v1
kind: Service
metadata:
  name: vrisingnodeport
spec:
  type: NodePort
  selector:
    app: vRisingServer
  ports:
  - name: gameport
    port: 9876
    protocol: UDP
    nodePort: 30876
    targetPort: 9876
  - name: rconport
    port: 9876
    protocol: TCP
    nodePort: 30876
    targetPort: 9876
  - name: queryport
    port: 9877
    protocol: UDP
    nodePort: 30877
    targetPort: 9877