name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker image with the commit hash as the tag
      - name: Build Docker image
        run: |
          COMMIT_HASH=$(git rev-parse --short HEAD)
          docker build -t ${{ secrets.DOCKER_USERNAME }}/vrising-server:$COMMIT_HASH .

      # Push the Docker image to Docker Hub
      - name: Push Docker image
        run: |
          COMMIT_HASH=$(git rev-parse --short HEAD)
          docker push ${{ secrets.DOCKER_USERNAME }}/vrising-server:$COMMIT_HASH
