name: Check for V Rising Updates

on:
  schedule:
    - cron: '0 0 * * 0' # Every Sunday at midnight
  workflow_dispatch:

jobs:
  check-vrising-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Get latest V Rising buildid
        id: vrising_build
        run: |
          LATEST_BUILD=$(curl -s https://api.steamcmd.net/v1/info/1828900 | jq -r '.data."1828900".depots.branches.public.buildid')
          echo "latest=$LATEST_BUILD" >> "$GITHUB_OUTPUT"

      - name: Update Dockerfile
        if: steps.vrising_build.outputs.latest != 'null' && steps.vrising_build.outputs.latest != ''
        run: |
          LATEST_BUILD="${{ steps.vrising_build.outputs.latest }}"
          sed -i "s/ARG VRISING_BUILD_ID=\".*\"/ARG VRISING_BUILD_ID=\"$LATEST_BUILD\"/" Dockerfile

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
        with:
          commit-message: "chore(deps): update v rising build to ${{ steps.vrising_build.outputs.latest }}"
          title: "Update V Rising Build ID to ${{ steps.vrising_build.outputs.latest }}"
          body: "Automated update of V Rising build ID in the Dockerfile to trigger a new image build."
          branch: "update-vrising"
          delete-branch: true
